### ISSUE TITLE
The proxy does not return exact status code from the service provider

### ISSUE THREAD

**Issue by DeeStarks** [globe-and-citizen/layer8-middleware#12]
I noticed making a request to an endpoint that doesn't exist on the service provider's end throws a `401 Unauthenticated` instead of the `404 Not found` from the server. See screenshots below:

| Proxy receives 404 from service provider | Browser receives 401 error from proxy |
| --- | --- |
| ![Screenshot from 2024-04-26 20-30-32](https://github.com/globe-and-citizen/layer8/assets/67328657/f31646b0-af6a-4d2b-9c95-d0b4fbf324ce) | ![Screenshot from 2024-04-26 20-31-42](https://github.com/globe-and-citizen/layer8/assets/67328657/83e6eb0d-6895-43ab-bc0d-7003673dc4e7)

**Comment by stravid87** [comment]
This issue is fixed in PR #79 "https://github.com/globe-and-citizen/layer8/pull/79"
